name: Comment Triggered Test
on:
  issue_comment:
    types: [created]
permissions: 'write-all'
jobs:
  benchmark:
    name: Integration Tests
    if: ${{ github.event.issue.pull_request && contains(fromJson('["MEMBER", "OWNER"]'), github.event.comment.author_association) && startsWith(github.event.comment.body, '/run-tests ') }}
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/github-script@v6
        name: Get PR branch
        id: issue
        with:
          script: |
            const pr = context.payload.issue.number
            const data = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr
            })
            return {
              ref: data.data.head.ref,
              sha: data.data.head.sha,
            }
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ fromJson(steps.issue.outputs.result).sha }}
      - run: bash comment_victim/test.sh
