name: Environment PR Check

on:
  pull_request_target:
    branches:
      - main
jobs:
   test:
     environment: Public CI
     runs-on: windows-latest
     steps:
       - name: Checkout from PR branch  
         uses: actions/checkout@v4
         with: 
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

       - name: Set Node.js 20.x for GitHub Action
         uses: actions/setup-node@v4
         with:
           node-version: 20.x

       - name: installing node_modules
         run: cd environment_example && npm install 

       - name: Build GitHub Action
         run: cd environment_example && npm run build
